on: push
name: build-and-push
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: macagauna117/devops-interview-workflow
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
