on: push

env:
  DOCKER_IMAGE: nginx
  K8S_NAMESPACE: web-server
  K8S_DEPLOYMENT: nginx

name: build-and-push
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: macagauna117/devops-interview-workflow
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}

  deploy-to-cluster:
      name: deploy to cluster
      runs-on: ubuntu-latest
      needs: build-and-push
      steps:
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: |
            kubectl set image deployment $K8S_DEPLOYMENT -n $K8S_NAMESPACE $K8S_DEPLOYMENT=macagauna117/devops-interview-workflow:${{ github.sha }}
            kubectl rollout status deployment/$K8S_DEPLOYMENT -n $K8S_NAMESPACE